[package]
name = "chains-rs"
version = "0.1.0"
edition = "2021"
authors = ["Pactus <info@pactus.org>"]
description = "Blockchain and asset definitions in Rust"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ezex-io/chains"
documentation = "https://docs.rs/chains-rs"
keywords = ["blockchain", "crypto", "assets", "web3", "cryptocurrency"]
categories = ["cryptography::cryptocurrencies"]

[dependencies]

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
